name: Metrics
on:
  schedule: [{ cron: "0 5 * * 1" }]
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # core
          token: ${{ secrets.METRICS_TOKEN }}
          user: tibimac
          template: classic
          config_padding: 16
          config_timezone: Europe/Paris
          config_order: base.header, introduction, base.activity+community, base.repositories, lines, languages, sponsorships, achievements
          # base
          base: header, activity, community, repositories, metadata
          base_indepth: true
          # lines
          plugin_lines: yes
          # languages
          plugin_languages: yes
          # sponsorships
          plugin_sponsorships: yes
          plugin_sponsorships_size: 32
          # achievements
          plugin_achievements: yes
